# Generated by Django 4.1.4 on 2022-12-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("received", "Received"),
                    ("started", "Started"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
